config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'boards#index'
  resources :boards do
    resources :comments, only: [:create]
  end
  resources :searches, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :comments 
  has_many :category_boards
  has_many :categories, through: :category_boards
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_boards
  has_many :boards, through: :category_boards
end

app/models/category_board.rb
class CategoryBoard < ApplicationRecord
  belongs_to :category
  belongs_to :board
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :board          
  belongs_to :user 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :boards   
  has_many :comments     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_category

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  private

  def set_category
    @categories = Category.all
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.includes(:user).page(params[:page]).per(5).order("created_at DESC")
  end

  def new
    @board = Board.new
  end

  def create
    if user_signed_in?
      @board = Board.create(board_params)
      redirect_to action: :index 
    else  
      redirect_to root_path
    end
  end  

  def show
    @board = Board.find(params[:id])
    @comment = Comment.new
    @comment_all = Comment.where(board_id: @board.id)
  end


  private

  def board_params
    params.require(:board).permit(:name, :text,:main_category,:sub_category).merge(user_id: current_user.id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create 
    if user_signed_in?
      @board = Board.find(params[:board_id])
      @comment = @board.comments.build(comment_params)
      @comment.save
      redirect_to board_path(@board) 
    else  
      redirect_to root_path
    end
  end

  private
  def comment_params #requireでreviewバリューを取得。premitで三つをキーとする安全面で保証されたハッシュを取得。mergaメソッドで分けられたハッシュを統合。requireでメソッドで取得したハッシュと結合
    params.require(:comment).permit(:name, :text).merge(board_id: params[:board_id], user_id: current_user.id)
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search

  def set_search
    if params[:q] != nil
      @search = Board.ransack(params[:q])
      @search_boards = @search.result.page(params[:page]).per(5).order("created_at DESC")
    else
      @search = Board.ransack(params[:q])
    end
  end

  def index
    @boards = Board.all
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/boards/_board.html.haml
.board-post-box
  = link_to board_path(board) do
    .board-post
      .board-post__name
        名前：
        = board.name
      .board-post__text  
        = board.text
      - if  board.main_category.present?
        .board-post__main_category 
          メインカテゴリ：
          = Category.find(board.main_category).name 
      - if  board.sub_category.present?
        .board-post__main_category 
          サブカテゴリ：
          = Category.find(board.sub_category).name 
    = render 'comments/comment'    

app/views/boards/index.html.haml
.board-post-index
  - if user_signed_in?
    .board-post-index-welcome.displayflex
      .board-post-index-text
        ようこそ
      .board-post-index-text
        = current_user.nickname
      .board-post-index-text  
        さん
      = link_to "ログアウト", destroy_user_session_path, method: :delete
  - else
    = link_to "ログイン", new_user_session_path, :class => 'post'
    = link_to "新規登録", new_user_registration_path, class: 'post'
  .board-post-index__logo
  .board-post-index__search  
    = link_to "記事を検索する", searches_path, class: 'get'
  .board-post-index__container
    .board-post-index__container__box
      - @boards.each do |board|
        = render partial: "board", locals: { board: board }
    = paginate(@boards)

app/views/boards/new.html.haml
.board-post-new
  = form_with model: @board, local: true, multiple: true do |f|
    .board-post-new__logo
    .board-post-new__container
      .input-box-name
        = f.label :name, class: 'input-box-name', for: "input-box-name-area"  do
          = f.text_field :name, class: "input-box-title-area", placeholder:"名前",id: "input-box-title-area", value: '', rows: 1
      .input-box-text  
        = f.label :text, class: 'input-box-text', for: "input-box-text-area" do         
          = f.text_area :text, class: "input-box-text-area", placeholder:"テキスト",id: "input-box-text-area", value: '', rows: 5
      .input-box-select-container
        .input-box-select-container-box
          メインカテゴリ 
        = f.collection_select(:main_category, @categories, :id, :name,{prompt: "--------"}, class: "input-box-select-area") 
        .input-box-select-container-box
          サブカテゴリ 
        = f.collection_select(:sub_category, @categories, :id, :name,{prompt: "--------"}, class: "input-box-select-area") 
        
      
      .input-box-caution
        投稿するにはユーザー登録・ログインする必要があります。
      .submit-box
      = f.submit '投稿する', class: 'form__contribute' 
    .main-box-footer-new

app/views/boards/show.html.haml
.board-post-index
  - if user_signed_in?
    ようこそ●●さん
    = link_to "ログアウト", destroy_user_session_path, method: :delete
  - else
    = link_to "ログイン", new_user_session_path, :class => 'post'
    = link_to "新規登録", new_user_registration_path, class: 'post'
  .board-post-index__logo
    投稿詳細
  .board-post-show__container.main-container 
    .board-post.main-container-box
      .board-post__name
        名前：
        = @board.name
      .board-post__text  
        = @board.text
      - if  @board.main_category.present?
        .board-post__main_category 
          メインカテゴリ：
          = Category.find(@board.main_category).name 
      - if  @board.sub_category.present?
        .board-post__main_category 
          サブカテゴリ：
          = Category.find(@board.sub_category).name   
    = render 'comments/comment'

app/views/comments/_comment.html.haml
- if @comment
  = form_for [@board, @comment], local: true do |f|
    .board-post-comment-list.main-container 
      - @comment_all.each do |comment|
        .board-post-comment-list__container.main-container-box-comment
          .board-post-comment-list__container__user
            .article-comment-user-nickname
              名前：
              = comment.name
          .board-post-comment-list__container__box
            .board-comment-text
              = comment.text
      .board-post-comment
        .board-post-comment__box
          .board-post-comment__box__name
            = f.text_area :name, placeholder: '名前を入力', style: 'width: 30%;height: 30px;'
          .board-post-comment__box__text
            = f.text_area :text, placeholder: '入力', style: 'width: 100%;height: 100px;'
      .input-box-form
        レスするにはユーザー登録・ログインする必要があります。
        = f.submit 'レスする', class: 'form__contribute'

app/views/layouts/_header.html.haml
.board-header
  .board-post-header-logo
    Engineer Test Bulletin Board
  .board-post-header-btn
    .board-post-header-btn-post
      = link_to "投稿する", new_board_path, method: :get
      = link_to "トップへ戻る", boards_path, method: :get
      

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .wrapper
      .header
        = render 'layouts/header'
      .main-body 
        .main-box
          = yield 
      .footer

app/views/searches/index.html.haml
.search-box
  = search_form_for @search, url: searches_path do |f|
    .search-box
      %form.form
      .keyword-search
        .input-box
          = f.text_field :text_or_name_cont_all, placeholder: 'キーワードを入力', class: 'header-search-text-area', maxlength: 20
          = f.submit ("検索") , class: 'headrer-search-btn'
          %span
    - if @search_boards      
      .search-result
        .search-result-container
          .search-result-container-box
            %p4 検索結果
            - if @search_boards.length >= 1  
              .search-result-heading-box
                = params[:q][:text_or_name_cont_all]
                の検索結果　
              - @search_boards.each do |board|      
                .board-post-box.main-container 
                  = link_to board_path(board) do
                    .board-post.main-container-box
                      .board-post__name
                        名前：
                        = board.name
                      .board-post__text  
                        = board.text
              = paginate(@search_boards)        
            - else            
           